### ISSUE TITLE
Some questions before I decide if I port my frontend to bui

### ISSUE THREAD

**Issue by Boscop** [astraw/bui-backend#4]
This project looks very interesting, but before I switch my existing frontend over to bui I have some questions:
1. Why does it use server-sent events instead of websockets? When will it be possible to use websockets instead?
1. How flexible is it, does it impose any restrictions on what the frontend can do? Or can it be a full featured web app that uses webgl, canvas, svg, localstorage etc.?
1. When to use bui instead of just writing a frontend in yew and backend with (rocket|rouille|hyper) + ws-rs (and then injecting the ws port into the page before serving, if the port is dynamic) or actix (to serve websockets on the same port)?
1. Will it ever support something like browser-sync, to reload all clients when the source changes (maybe using the `notify` crate like `cargo-watch`)?

My current project uses a frontend written in polymer, I'm using browser-sync to auto-reload the app when the files change on disk, but I want to rewrite the frontend in Rust with yew (for wasm) so that I can re-use code and types from my backend and get static type safety.
My server side uses ws-rs and I want to keep using websockets because somewhere I've read that they have lower latency than server-sent events, is that true? 
Btw, this project is a DJing/VJing application and needs the lowest possible latency.

**Comment by astraw** [comment]
Interesting questions.

> Why does it use server-sent events instead of websockets? When will it be possible to use websockets instead?

Actually, pre-history versions of bui-backend used websockets. I switched to server-sent events because websockets were not supported within the hyper crate. Also, as far as I understand it, the http2 standard will not support websockets. On the pro side for websockets, it supports binary data, which must be encoded over server-sent events. I do not plan to add webockets support myself, but would be happy to accept a PR which would implement them under a cargo feature flag and would be server-sent events also under such a flag. (And evenutally `ReadableStream` could also be made available this way.)

> How flexible is it, does it impose any restrictions on what the frontend can do? Or can it be a full featured web app that uses webgl, canvas, svg, localstorage etc.?

I think these questions you are really asking about the yew framework. In my experience, I think most of those things can be made to work, but I just submitted PRs to support mouse-move events and textarea elements, so certainly there are some APIs which are not wrapped yet. 

> When to use bui instead of just writing a frontend in yew and backend with (rocket|rouille|hyper) + ws-rs (and then injecting the ws port into the page before serving, if the port is dynamic) or actix (to serve websockets on the same port)?

I think the dividing line is if you want to keep things simple vs develop a "real web app". Simple in the case of bui-backend is that the entire datastore is shared between the server and clients, including updates. This keeps bui-backends hopefully simpler than a full blown web app but at the cost of, for example, not being able to distribute information selectively to specific clients. (That said, there is an "escape hatch" where each connection is given a unique ID and can then be accessed outside bui-backend.) 

> Will it ever support something like browser-sync, to reload all clients when the source changes (maybe using the notify crate like cargo-watch)?

This would be cool to add. I haven't tried but would love a PR on the demos (fine to focus on the yew demo).

**Comment by Boscop** [comment]
> the http2 standard will not support websockets.

Why is this relevant for this crate, which is designed for UIs for applications where the UI and the application both run on localhost, so there won't be any HTTPS, and http2 doesn't work without HTTPS.
And even after HTTP2 is used on all websites, Websockets will still be supported by browsers, right?

> I think the dividing line is if you want to keep things simple vs develop a "real web app".

My web frontend is basically a SPA frontend for my DJ/VJ Rust app and there will only be 1 client (browser on my android tablet) at a time, except when I'm reloading the page. Or sometimes I also open the frontend in my laptop browser. Currently all clients (usually just 1) get the same state updates. 
I do this by integrating msgs (coming from the core to the webui) over time in a state struct, and when a new client connects, I serialize the state into messages and send them to the client, and after that it just gets each msg as it comes from the core. So I have a msg enum with a case for every state struct field.
I serialize my msg enums as json (2 enums, one for each direction).

I want to keep things as simple as possible and only as complex as necessary..

Btw, I'm running into this issue with ws-rs (high CPU usage): https://github.com/housleyjk/ws-rs/issues/178#issuecomment-339539782
Any idea why that could be?

**Comment by astraw** [comment]
bui-backend is not necessarily for running purely on localhost, but I agree that http and websockets will likely never be replaced by http2. So, as I said, I would gladly review a PR that adds websocket support under a cargo feature flag. This is particularly attractive because websockets would not require encoding binary data, which is unfortunately required for server-sent events.

Your design with a different enum for each communication direction seems completely reasonable. Keeping shared state with bui-backend would be a different design, indeed, and not necessarily better. If your design already synchronizes state in frontend and backend then you have solved the major problem that bui-backend also solves and your method sends less data on the wire because currently bui-backend serializes the entire struct at each update.

There could be a simple methods of reducing data sent on each change by tracking what the other side already knows and sending just the differences, but I haven't implemented anything like that. In the longer run, I am interested in making [`raii-change-tracker`](https://github.com/astraw/raii-change-tracker) (responsible for controlling access to the state and notifying on updates) or its replacement support finer grained change notification e.g. by investigating better approaches to shared mutable data stores such as by using conflict-free replicated data types.

No idea about your problem with ws-rs, but it seems that doing git-bisect could help you find the responsible change.

**Comment by astraw** [comment]
I'm closing this for now, but feel free to re-open if you have further comments.
